CREATE TABLE STUDENT (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    marks INT
);

INSERT INTO STUDENT VALUES (1, 'Ravi', 85);
INSERT INTO STUDENT VALUES (2, 'Anita', 90);
INSERT INTO STUDENT VALUES (3, 'Kiran', 78);

SELECT * FROM STUDENT;